version: '3'
services:
  ganachecli:
    build: ./ganache
    ports:
      - '8545:8545'
    networks:
      - backend
    volumes:
      - ./ganache_data:/ganache_data
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
  mongo_seed:
    build: ./mongo_seed
    networks:
      - backend
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - ./client:/client
  server:
    build: .
    ports:
      - 6000:6000
    networks:
      - backend
    depends_on:
      - ganachecli
      - mongo
    entrypoint: ./server_start.sh
networks:
  backend:
    driver: bridge
